name: Create new release

on:
  push:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest

    env:
      TimeZone: "Asia/Tokyo"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # ブランチに含まれるファイルをzipファイルにまとめる
      - name: Create zip file
        id: zip_file
        run: |
          git ls-files | grep -vE ".gitattributes" | zip -q -@ release.zip
          echo "zip_file=release.zip" >> $GITHUB_OUTPUT

      # 前回のReleaseに使用されたタグをfetch
      - name: Fetch previous tag
        id: previous_tag
        run: |
          echo "previous_tag=$(curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)" >> $GITHUB_OUTPUT

      # 今回のReleaseに使用するタグを生成
      - name: Create release tag
        id: release_tag
        run: |
          today=$(date +'%Y.%m.%d')
          pre_release_date=$(echo ${{ steps.previous_tag.outputs.previous_tag }} | awk -F'-' '{print $1}')
          pre_release_count=$(echo ${{ steps.previous_tag.outputs.previous_tag }} | awk -F'-' '{print $2}')
          if [[ ! $pre_release_date = $today ]]; then
            echo "init count"
            pre_release_count=0
          fi
          echo "::set-output name=release_tag::$today-$(($pre_release_count + 1))"

      - name: Debug
        run: |
          echo "Release Tag: ${{ steps.release_tag.outputs.release_tag }}" # Log release tag

      # Releaseを作成
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.release_tag.outputs.release_tag }}
          release_name: ${{ steps.release_tag.outputs.release_tag }}
          draft: false
          prerelease: false

      # Releaseにzipファイルを添付
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './output/release.zip'
          asset_name: ${{ github.repository }}_${{ steps.zip_file.outputs.release_tag }}.zip
          asset_content_type: application/zip